name: Vérification de la qualité du code

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer les dépendances du projet
        run: npm install --save-dev  @eslint/js prettier 

      - name: Vérification ESLint
        run: npm run lint

      - name: Lancer les test automatisés
        run: npm test
#VERIFIE LA GENERICIT2 DU CODE FORMATTAGE ETC...